# Generated by Django 3.1.7 on 2021-04-02 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(max_length=100)),
                ('tariff', models.CharField(max_length=100)),
                ('calculated_price', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('adapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.adapter')),
            ],
        ),
    ]
